### ISSUE TITLE
Solve for implied volatility (IV) given actual option price

### ISSUE THREAD

**Issue by pavinjosdev** [CarloLepelaars/blackscholes#21]
Hello @CarloLepelaars 👋

Thanks for creating this very useful library 💯

Since most of the option strategies are either buying or selling volatility, I was wondering if it's possible to substitute the actual option price in the formula and solve for sigma / IV? 🤔

A [website](https://www.option-price.com/documentation.php#impliedvolatility) I found on the web states:

> It is impossible to reverse the Black Scholes formula and solve for volatility.
I use the market price as the output for Black and Scholes and use this method to solve for the volatility input that would generate the price that equals the market price.

Edit 1:
But in the book *Trading Option Greeks (2nd ed.)* by Dan Passarelli, it says the option pricing formula can be thought of as an algebraic equation and traders (or, rather their programs) could solve for IV by substituting the option's current market price. Not sure who to believe, may be they are both correct and the website's brute force method of solving IV is what's used by trading software. I hope you could shed some light on this, as I'm not familiar with the advanced math used in the code here! 😵‍💫

![iv-1](https://github.com/user-attachments/assets/cca608f4-a66a-4dc9-8384-f110962304e9)
![iv-2](https://github.com/user-attachments/assets/e10f1780-eda2-4f9a-bc64-48a91a61ca88)

**Comment by CarloLepelaars** [comment]
Hi @pavinjosdev, thank you for the kind words! 

I think the paragraphs from the book you're reading are correct. It seems to me if you have the output and all outputs except for volatility you can solve for volatility. This will give you a good estimate (i.e. implied volatility (IV)). There are multiple open source libraries that I think have pretty good solution for calculating IV.
