### ISSUE TITLE
Inconsistencies in value units

### ISSUE THREAD

**Issue by pavinjosdev** [CarloLepelaars/blackscholes#22]
Hello @CarloLepelaars 👋,

Sorry for creating multiple "issues", though my other one was a question and this is something I can submit a PR for if you agree. 🙂

I noticed some inconsistencies in the units used for calculating the core greeks (perhaps affecting others as well but I don't know much about them):
1. Delta and Gamma: expressed as percentage in decimal form. This is expected and the most common representation used by traders ✅
2. Vega and Rho: expressed as regular percentage. This is confusing and conflicts with delta and gamma's representation in decimal form. Not a common representation used by traders ❌
3. Theta: expressed as annualized value. It's okay but also not the common representation of daily value based on a 7 day week used by traders. This should be made clear in the docs or else changed into a daily value ⚠️

Thank you for creating this awesome library 💯

**Comment by CarloLepelaars** [comment]
Thank you @pavinjosdev, was not aware of this about Vega and Rho. It would be great if you want to contribute a PR. As long as we document it well I think it will be improvement. We can also clarify the representation for Delta, Gamma and Theta.

**Comment by pavinjosdev** [comment]
Now that I think about it, documenting the units for these greeks would be a better choice, otherwise changing the units would be a major breaking change for existing users of the library.

I will submit the PR soon 😸

**Comment by CarloLepelaars** [comment]
hi @pavinjosdev, thanks again for your help! I just made a little graphical interface for the Black Scholes calculations. Feedback is appreciated! Among other things I'm thinking off adding a CSV export button.

https://carlo.ai/tools/blackscholes

**Comment by pavinjosdev** [comment]
@CarloLepelaars Really cool, thanks! 🚀

Only things I wish were different in the GUI version are the units:
- T could be in days
- r, q, and sigma could be in regular percentage

That would make it easier for normal people to use, but otherwise great job 💯

Bonus if it could solve for sigma (IV) provided CMP of call/put. 🎉

I implemented it in one of my backtest scripts using a small function:

```python
# Function to get theoretical/fair value option price and delta according to BSM formula
def get_theo(opt_type, spot_price, strike_price, dte, iv):
    if opt_type == "call":
        opt = BlackScholesCall(S=spot_price, K=strike_price, T=dte/365, r=risk_free_rate/100, sigma=iv/100, q=0)
    elif opt_type == "put":
        opt = BlackScholesPut(S=spot_price, K=strike_price, T=dte/365, r=risk_free_rate/100, sigma=iv/100, q=0)
    return round(opt.price(), 2), round(opt.delta(), 2)

# Function to get option strike's IV provided market price of option
def get_iv(opt_price, opt_type, spot_price, strike_price, dte):
    iv_start = 0.001
    iv_end = iv_start + 1000
    iv_mid = (iv_start + iv_end) / 2
    while True:
        p_mid = get_theo(opt_type, spot_price, strike_price, dte, iv_mid)[0]
        if round(opt_price) == round(p_mid):
            break
        elif round(opt_price) < round(p_mid):
            iv_end = iv_mid
            iv_mid = (iv_start + iv_end) / 2
        elif round(opt_price) > round(p_mid):
            iv_start = iv_mid
            iv_mid = (iv_start + iv_end) / 2
        if iv_mid < 0.1 or iv_mid > 999.9:
            break
    return round(iv_mid, 1)
```
